spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: PASSWORD
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: UTC